### ISSUE TITLE
user stuck on a blank screen when not logged in

### ISSUE THREAD

**Issue by leo2d** [Kareadita/Kavita-webui#234]
**Description:**
Opening the browser to http://<kavita_server>:5000 without being logged in displays a blank page with nothing but the Kavita header.

Reproduced on Chrome, Edge, and Firefox.

**Steps to reproduce:**
- logout if you're logged in
- clear local storage data
- open localhost:4200 if debugging or  http://<kavita_server>:5000  in releases

**Tech details:**

For some reason, this check is not working: 

![image](https://user-images.githubusercontent.com/28194654/121760542-b78fea00-cb01-11eb-97fe-cf1da2fc586e.png)

It's causing an error on the console and the redirection to the login screen is not happening as it should, so the user stays on a blank screen with a navbar.

![image](https://user-images.githubusercontent.com/28194654/121760774-cc20b200-cb02-11eb-8704-1c6dcbf39b77.png)

**Comment by majora2007** [comment]
Looks like I messed up and it should be an && instead of ||
